### ISSUE TITLE
Add border below tabs on main screen (light theme)

### ISSUE THREAD

**Issue by elioqoshi** [Vavassor/Tusky#113] opened 2017-04-09 15:50 UTC
There is currently no border to distinguish the bottom of the tabs and the timeline right now. In Twitter, there is a very thin gradient to visualize that. Can we add something similar here?
![twitter](https://cloud.githubusercontent.com/assets/5436686/24838679/12a5518a-1d4d-11e7-8241-b200981c200b.jpg)

**Comment by elioqoshi** [comment] 2017-04-09 15:52
Note: This seems to be only in the light theme.

**Comment by daycode** [comment] 2017-04-09 16:14
duplicate of #107 ? 🤔

**Comment by elioqoshi** [comment] 2017-04-09 16:36
Yep, sorry, didn't notice that.

**Comment by daycode** [comment] 2017-04-09 16:38
so, can you close this issue ? 😃

**Closed** 2017-04-09 18:00 UTC
