### ISSUE TITLE
Interface momentarily error: superposition of toots

### ISSUE THREAD

**Issue by moshpirit** [Vavassor/Tusky#305] opened 2017-06-05 09:32 UTC
I'm using ForkHub on my phone so I can't check anything of the list, sorry.

This is a very weird thing that just has happened to me and I'm not sure if will appear again. I was refreshing the TL and scrolling a bit, if happens again I'll let you know!

Thank you so much for everything!

![](https://s9.postimg.org/rsvt25fhb/Screenshot_20170605-100715.png)

**Comment by Vavassor** [comment] 2017-06-05 21:22
This is a duplicate of Issue #20.

Two visual copies overlaid like this has been a symptom of different problems in the past, but since it happened on refresh and scroll it seems to be the same issue.

**Closed by Vavassor** 2017-06-05 21:22 UTC
Labels: bug, duplicate

**Comment by moshpirit** [comment] 2017-06-05 21:28
Oh, sorry and thank you so much!!
