### ISSUE TITLE
Provide matching users when @mentioning

### ISSUE THREAD

**Issue by wxl** [Vavassor/Tusky#276] opened 2017-05-06 17:52 UTC
In the web app, if you @mention someone, it provides a list of matching users. With Tusky, you just have to remember.

**Comment by daycode** [comment] 2017-05-06 21:48
Please, search in issues before opening one 🙏 
this is duplicate of #103

**Comment by wxl** [comment] 2017-05-06 22:02
I did search, too! 🤦🏽‍♂️

**Closed** 2017-05-06 22:02 UTC
