### ISSUE TITLE
ability to swipe through photos

### ISSUE THREAD

**Issue by govvin** [Vavassor/Tusky#344] opened 2017-07-15 22:18 UTC
It would be nice to support swipe gestures when browsing through multiple photos

**Comment by Vavassor** [comment] 2017-07-17 00:42
This was added in commit f37bb694f186fde6eadbe5743b3fa6b92e404f00, it just hasn't been released yet. It's in the current beta and it'll be in version 1.1.4 when that comes out.

(Also, technically this is a duplicate of the closed issue #66.)

**Closed by Vavassor** 2017-07-17 00:42 UTC
Labels: duplicate
