### ISSUE TITLE
Not able to paste string into "Search Contact"

### ISSUE THREAD

**Issue by yookoala** [Vavassor/Tusky#146] opened 2017-04-13 04:44 UTC
You cannot pop the "paste / select all" pop out box if you long press the "Search Contact" text input.

That's what user usually expects. And it would be easier to paste text to search then to manually type it. Especially when you see a Mastodon / GNUSocial address from another app (e.g. browser), you'd naturally want to just copy it and paste to "Search Contact". Instead, you'd have to memorize and manually type it.

**Comment by Vavassor** [comment] 2017-04-14 22:42
This is a duplicate of #94.

**Comment by daycode** [comment] 2017-04-18 17:51
as this issue is a duplicate of another open, can your close this one ? 😉

**Closed** 2017-04-19 06:07 UTC
Labels: duplicate
