### ISSUE TITLE
Detect user account links in user bios

### ISSUE THREAD

**Issue by raphaelm** [Vavassor/Tusky#171] opened 2017-04-15 19:01 UTC
If another user account is mentioned in a user bio, a click on it should open in the app and not in the browser.

**Comment by Vavassor** [comment] 2017-04-16 22:41
I don't remember doing this for hash tags in bios, either, so probably doing both at the same time would be a good plan.

**Comment by charlag** [comment] 2017-11-11 08:16
This is a duplicate of #384

**Closed by charlag** 2017-11-11 08:16 UTC
Labels: enhancement
