### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by milesmcc** [Vavassor/Tusky#191] opened 2017-04-18 00:34 UTC
Hello wonderful Tusky contributors & maintainer(s),

Because Tusky is an open-source Android app, it would be great if it were included on the F-Droid FOSS app store.

Is this something that would be considered?

Regards,
Miles

**Comment by Vavassor** [comment] 2017-04-18 01:32
This is kiiind of a duplicate of #39? The short answer is yes, I'm going to make a version for F-Droid soon.

The reason it was originally pulled from there is because I chose to use Firebase for push notifications, which is a proprietary service & library that's incompatible with F-Droid's build system.

When I put it back on F-Droid it'll be a separate version with polling-style notifications like used during Tusky's alpha phase. I'm planning to hopefully replace Firebase in the main version with a FOSS solution for push notifications, so I can have the same version on F-Droid as elsewhere. But that's going to take a long time, so that's further down the road.

**Comment by milesmcc** [comment] 2017-04-18 01:44
Glad to hear you plan on putting it back on F-Droid and moving to a FOSS push system.

Looking forward to seeing what comes down the road with this project!

**Comment by rodneyrod** [comment] 2017-04-18 14:26
@Vavassor will it be using the same build signature as the old F-Droid build?

**Comment by daycode** [comment] 2017-04-18 16:11
as this issue is a duplicate of another open, can you close this one ? 😄

**Closed** 2017-04-18 16:16 UTC

**Comment by IzzySoft** [comment] 2017-04-20 18:43
@rodneyrod not possible, as F-Droid builds from sources. Neither do they have the devs keys, nor vice versa. If the `.apk` were available here via Github (best via the project's `releases/` page, attached to the resp. tags) I could automatically grab it for [my F-Droid compatible repo](https://android.izzysoft.de/repo). That then would mean it shares the signature with the Playstore version, as both are signed by the same dev.
