### ISSUE TITLE
Visual feedback for "follow" button

### ISSUE THREAD

**Issue by divergentdave** [Vavassor/Tusky#105] opened 2017-04-08 17:48 UTC
When viewing a user's profile, if I tap the circular follow button in the bottom right corner, there is no visual feedback. If I look in the menu or go back and reopen the profile, then I see that I have successfully followed the person. Once I have followed them, the circular button in the bottom right doesn't show up on subsequent visits. However, I would like for the button to disappear right away, as an indication that tapping the button worked.

**Comment by connyduck** [comment] 2017-04-08 17:58
Duplicate of https://github.com/Vavassor/Tusky/issues/42
The fix will be in the next release

**Comment by Vavassor** [comment] 2017-04-29 01:52
This was fixed as of 3a0fc9d3db1dd032235e7220bc4410e06fb94a12.

**Closed by Vavassor** 2017-04-29 01:52 UTC
Labels: duplicate
