### ISSUE TITLE
No auto-correct when writting a toot

### ISSUE THREAD

**Issue by matlink** [Vavassor/Tusky#382] opened 2017-09-05 19:46 UTC
There is no auto-correct available when tooting. It looks like coming from the @ completion feature, which kinda disable auto-completion for the keyboard.
Typing in the search bar is not impacted, there is auto-completion.

LineageOS 14.1, AOSP keyboard, French layout and dictionary.

**Comment by nailyk-fr** [comment] 2017-09-11 17:39
Exact same setup, same problem. Previous fdroid version was working fine. 
Cannot find relevant keyword with github search. Probably search index is too old, as usual. 
Will try to sync the repo to make some blame in the coming days.

**Comment by Gildas-GH** [comment] 2017-09-30 20:23
Same problem on Android 6.0 on an Acer device with the default ROM, I am using AnySoftKeyboard with the Franch layout.

**Comment by connyduck** [comment] 2017-10-22 10:02
Duplicate of https://github.com/Vavassor/Tusky/issues/374

**Closed by connyduck** 2017-10-22 10:02 UTC

**Comment by nailyk-fr** [comment] 2017-10-24 07:37
Confirmed working. 
Thanks :)
