### ISSUE TITLE
Search field doesn't work for hashtags?

### ISSUE THREAD

**Issue by JamesHealdUK** [Vavassor/Tusky#313] opened 2017-06-16 21:52 UTC
Whenever I make a search using the top bar, I only get user results, is it currently possible to search by hashtags?

Cheers.

**Comment by Vavassor** [comment] 2017-06-17 00:41
This a duplicate of Issue #44.
Currently there's no way to search tags: only accounts. Sorry!

**Closed by Vavassor** 2017-06-17 00:41 UTC
Labels: duplicate
