### ISSUE TITLE
Crash when viewing a particular post's media

### ISSUE THREAD

**Issue by forivall** [Vavassor/Tusky#277] opened 2017-05-07 15:57 UTC
Final location: https://pictor.ialis.me/media_attachments/files/000/052/596/original/808b0d5604194f38.jpg
Toot: https://soc.ialis.me/users/Famine/updates/6896
```
Famine@soc.ialis.me - French elections in a nutshell. https://soc.ialis.me/media/oy3zfwOgKLg04Ri7B3w
```
[Todo: insert screenshot here]

**Comment by torrentcome** [comment] 2017-05-12 13:31
Hi,

I'm testing works without crashing, i believe it's another problem
@Vavassor : We don't have any Crashlytics tool's or other crash-tracing ? (will be great to have one)

Thks

**Comment by connyduck** [comment] 2017-05-23 19:47
Can not reproduce, any additional information?

**Comment by forivall** [comment] 2017-05-25 00:49
It doesn't have to do with the hosting, but i can still reproduce the crash by going to Famine's toot stream and tapping on that image that doesn't load in the timeline.

I was able to run `logcat` this time and got
```
05-24 17:45:49.803  7958  7958 E UncaughtException: 
05-24 17:45:49.803  7958  7958 E UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at com.keylesspalace.tusky.ad.b(SFragment.java:273)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at com.keylesspalace.tusky.ao.a(TimelineFragment.java:346)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at com.keylesspalace.tusky.ai$1.onClick(StatusViewHolder.java:220)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at android.view.View.performClick(View.java:5637)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at android.view.View$PerformClick.run(View.java:22429)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at android.os.Handler.handleCallback(Handler.java:751)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at android.os.Looper.loop(Looper.java:154)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at java.lang.reflect.Method.invoke(Native Method)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-24 17:45:49.803  7958  7958 E UncaughtException: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-24 17:45:49.824   519   662 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
05-24 17:45:50.043  7958  7958 E AndroidRuntime: FATAL EXCEPTION: main
05-24 17:45:50.043  7958  7958 E AndroidRuntime: Process: com.keylesspalace.tusky, PID: 7958
05-24 17:45:50.043  7958  7958 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at com.keylesspalace.tusky.ad.b(SFragment.java:273)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at com.keylesspalace.tusky.ao.a(TimelineFragment.java:346)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at com.keylesspalace.tusky.ai$1.onClick(StatusViewHolder.java:220)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22429)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-24 17:45:50.043  7958  7958 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-24 17:45:50.046   889  3589 W ActivityManager:   Force finishing activity com.keylesspalace.tusky/.AccountActivity
```
I don't know the masto api, but perhaps if you can look at it and see if it returns anything unexpected for that post.

**Comment by connyduck** [comment] 2017-05-25 15:00
Ah I see, thank you for the report! This is a duplicate of https://github.com/Vavassor/Tusky/issues/265 and is fixed in https://github.com/Vavassor/Tusky/pull/266
Wait for the next release :)

**Closed** 2017-07-01 22:02 UTC
Labels: bug
