### ISSUE TITLE
Disappearing image URLs

### ISSUE THREAD

**Issue by averageunicorn** [Vavassor/Tusky#380] opened 2017-08-31 15:21 UTC
– Adding more than one image deletes the URL of the image before, so only the URL of the last one remains. I think this worked until recently, actually I was only going to report it for camera, but when I tried adding more than one picture from file manager today, the same thing happened.

– Switching to another app after adding an image deletes the image URL.

– Switching between landscape and portrait deletes the image URL. 

The pictures post just fine, but afaik missing image URLs (can?) mean that they don't federate.

I'm using version 1.1.4 with Android 6.0.1 on an Asus Zenfone Laser.

**Comment by charlag** [comment] 2017-10-19 08:49
@averageunicorn I've tried it on the latest dev build and I was not able to reproduce bug with more than one image.
With rotation it actually uploaded the image again!
Will look into this.

**Comment by connyduck** [comment] 2017-10-28 20:26
should be fixed https://github.com/Vavassor/Tusky/pull/425

**Closed by connyduck** 2017-10-28 20:26 UTC
Labels: bug
