### ISSUE TITLE
Followers list on profile doesn't display all followers

### ISSUE THREAD

**Issue by PhotonQyv** [Vavassor/Tusky#229] opened 2017-04-24 10:14 UTC
I wanted to see how many bots were following me, and ended up logging in to the web client to find out, because there are a whole chunk of followers missing from the followers list in Tusky.

Did a bit of investigation, it's not instance-related, nor is it linked to whether I follow-back.

Same issue affects Follows list.

**Comment by nailyk-fr** [comment] 2017-11-23 14:01
AFAICT this is by 'design'. Into tusky or webUI you will only display followers/following on your instance. 
You need to open in browser, outside of the mastodon webUI to see them. 
IIRC there is an issue for this on Mastodon github.

**Comment by charlag** [comment] 2018-01-08 20:13
@connyduck is this an issue on our side (is this an issue at all?)

**Comment by connyduck** [comment] 2018-01-08 21:09
I honestly have no idea. Never seen it, cannot reproduce.

**Comment by nailyk-fr** [comment] 2018-01-08 21:12
This is a mastodon issue. 
You only see followers followed by you too or on your instance. 



![capture d ecran - 08012018 - 22 11 10](https://user-images.githubusercontent.com/16372405/34692618-01c39e02-f4c1-11e7-9fe7-312e9f1d0a02.png)
![capture d ecran - 08012018 - 22 11 42](https://user-images.githubusercontent.com/16372405/34692620-01dda81a-f4c1-11e7-9954-6e748ff4dc49.png)

**Comment by charlag** [comment] 2018-01-08 21:13
Okay, let's close it then, feel free to reopen

**Closed by charlag** 2018-01-08 21:13 UTC
