### ISSUE TITLE
Allow to switch between users

### ISSUE THREAD

**Issue by rixx** [Vavassor/Tusky#161] opened 2017-04-15 10:59 UTC
It would be tremendously useful if I could use both my management account and my regular account from Tusky.

**Comment by alerque** [comment] 2017-04-15 13:44
This is a duplicate of #54. Whether two accounts on the same instance or accounts across multiple instances the needed functionality is the same.

**Comment by alerque** [comment] 2017-04-19 11:40
@Vavassor This can be closed entirely as a pointer to the duplicate, you don't need multiple open issues for the same action item.

**Closed** 2017-04-19 12:45 UTC
Labels: duplicate

**Comment by Vavassor** [comment] 2017-04-19 17:46
@alerque You're right. I wasn't thinking of how it'd be confusing. I was just going to close both when resolved, but that makes more sense.
